debug: false
likelihood:
  ygk_like.ygkLike:
    HM_correction: halofit
    M0_track: true
    bins:
    - name: LOWZ__0
    - name: LOWZ__1
    - name: LOWZ__2
    - name: LOWZ__3
    - name: LOWZ__4
    - name: LOWZ__5
    - name: YMILCA
    - name: KAPPA
    bz_model: HaloModel
    cm_name: Ishiyama21
    defaults:
      LOWZ__1:
        lmin: 10
      LOWZ__2:
        lmin: 10
      LOWZ__3:
        lmin: 10
      LOWZ__4:
        lmin: 10
      LOWZ__5:
        lmin: 10
      kmax: 1.0
      lmax: 1024
      lmin: 0
    hb_name: Tinker10
    ia_model: IANone
    input_file: data/saccfiles/cls_cov.fits
    input_params_prefix: ygk
    mdef_name: 500c
    mf_name: Tinker10
    ns_independent: true
    nside: 1024
    nz_model: NzShiftWidth
    shape_model: ShapeNone
    twopoints:
    - bins:
      - LOWZ__3
      - LOWZ__3
    - bins:
      - LOWZ__3
      - YMILCA
    - bins:
      - LOWZ__3
      - KAPPA
output: chains/gyksrA_Nsat/gyksrA_Nsat_3/cobaya
params:
  Omega_b: 0.048974682
  Omega_c: 0.26066676
  h: 0.6766
  m_nu: 0.0
  n_s: 0.9665
  sigma8:
    latex: \sigma_8
    prior:
      max: 1.5
      min: 0.2
    proposal: 0.02
    ref:
      dist: norm
      loc: 0.8102
      scale: 0.02
  ygk_Ahmc:
    latex: A_{\rm HMC}
    prior:
      max: 2.0
      min: 0.1
    proposal: 0.01
    ref:
      dist: norm
      loc: 1.0
      scale: 0.01
  ygk_LOWZ__0_b0: 2.0
  ygk_LOWZ__0_b1: 2.0
  ygk_LOWZ__0_b2: 0.0
  ygk_LOWZ__0_bp: 0.0
  ygk_LOWZ__0_bs: 0.0
  ygk_LOWZ__0_dz: 0.0
  ygk_LOWZ__0_lM1_0: 14.082529
  ygk_LOWZ__0_lMmin_0: 12.602721
  ygk_LOWZ__0_wz: 1.0
  ygk_LOWZ__1_b0: 2.0
  ygk_LOWZ__1_b1: 2.0
  ygk_LOWZ__1_b2: 0.0
  ygk_LOWZ__1_bp: 0.0
  ygk_LOWZ__1_bs: 0.0
  ygk_LOWZ__1_dz: 0.0
  ygk_LOWZ__1_lM1_0: 12.9802
  ygk_LOWZ__1_lMmin_0: 11.653036
  ygk_LOWZ__1_wz: 1.0
  ygk_LOWZ__2_b0: 2.0
  ygk_LOWZ__2_b1: 2.0
  ygk_LOWZ__2_b2: 0.0
  ygk_LOWZ__2_bp: 0.0
  ygk_LOWZ__2_bs: 0.0
  ygk_LOWZ__2_dz: 0.0
  ygk_LOWZ__2_lM1_0: 13.158662
  ygk_LOWZ__2_lMmin_0: 11.869872
  ygk_LOWZ__2_wz: 1.0
  ygk_LOWZ__3_b0: 2.0
  ygk_LOWZ__3_b1: 2.0
  ygk_LOWZ__3_b2: 0.0
  ygk_LOWZ__3_bp: 0.0
  ygk_LOWZ__3_bs: 0.0
  ygk_LOWZ__3_dz: 0.0
  ygk_LOWZ__3_lM1_0:
    latex: \log_{10}M_{1}
    prior:
      max: 15
      min: 8.0
    proposal: 0.005
    ref:
      dist: norm
      loc: 13.364201
      scale: 0.1
  ygk_LOWZ__3_lMmin_0:
    latex: \log_{10}M_{\rm min}
    prior:
      max: 15
      min: 8.0
    proposal: 0.005
    ref:
      dist: norm
      loc: 12.069004
      scale: 0.1
  ygk_LOWZ__3_wz: 1.0
  ygk_LOWZ__4_b0: 2.0
  ygk_LOWZ__4_b1: 2.0
  ygk_LOWZ__4_b2: 0.0
  ygk_LOWZ__4_bp: 0.0
  ygk_LOWZ__4_bs: 0.0
  ygk_LOWZ__4_dz: 0.0
  ygk_LOWZ__4_lM1_0: 13.388862
  ygk_LOWZ__4_lMmin_0: 12.114722
  ygk_LOWZ__4_wz: 1.0
  ygk_LOWZ__5_b0: 2.0
  ygk_LOWZ__5_b1: 2.0
  ygk_LOWZ__5_b2: 0.0
  ygk_LOWZ__5_bp: 0.0
  ygk_LOWZ__5_bs: 0.0
  ygk_LOWZ__5_dz: 0.0
  ygk_LOWZ__5_lM1_0: 13.035974
  ygk_LOWZ__5_lMmin_0: 12.09721
  ygk_LOWZ__5_wz: 1.0
  ygk_alpha: 1.0
  ygk_k_1h_suppress: 0.01
  ygk_mass_bias:
    latex: 1-b_H
    prior:
      max: 1.15
      min: 0.005
    proposal: 0.005
    ref:
      dist: norm
      loc: 0.75
      scale: 0.002
  ygk_rhogm: 0.0
  ygk_rhogy:
    latex: \rho_{gy}
    prior:
      max: 1.0
      min: -1.0
    proposal: 0.01
    ref:
      dist: norm
      loc: -0.5
      scale: 0.01
  ygk_siglM_0: 0.345
sampler:
  mcmc:
    burn_in: 10
    learn_proposal: true
    max_samples: 30000
theory:
  ygk_like.CCL:
    baryons_pk: nobaryons
    matter_pk: halofit
    transfer_function: bacco
